<?php 
//MODULE DE HOOK NS  


function NsHook_form_alter(&$form, &$form_state, $form_id) {


	global $base_url;

	if (isset($form['type']) && $form['type']['#value'] == 'balade') {
	
		drupal_set_message(t("Nouveau ! <br/> Pour toutes les images (sauf celle Haute qualité) il est possible de réduire le poid des images avec <a href='https://tinypng.com/' target='_blank'>Tiny PNG</a>"), "status");

		//alter title
		$form['title']['#title'] = 'Titre de la balade <small class="label_title">(conserver le caractère séparateur "-" pour l\'affichage de la deuxième ligne sur mobile, voir <a target="_blank" href="'.$base_url.'/sites/all/modules/nsModules/NsHook/img/screen_tuto_second_line.jpg" alt="voir exemple" title="voir exemple">exemple</a>.)</small>';

		//alter field_balade_teaser 
		$form['field_balade_teaser']['und'][0]['#title'] = 'Ancienne description <span class="textAide">( Assurez-vous de saisir de champs sous le format Plain text )</span>';
		
		//Alter field_esp_ces
		$form['field_esp_ces']['und']['#title'] = 'Liste des espèces <span class="textAide">  - Cochez les espèces présente dans votre balade.</span>';
		
		foreach ($form['field_esp_ces']['und']['#options'] as $key => $value) {
			
			$form['field_esp_ces']['und']['#options'][$key] = "<a href='$base_url/node/$key'>$value</a>";
		
		}

	
	
	}else if (isset($form['type']) && $form['type']['#value'] == 'espece') {
	
		drupal_set_message(t("Nouveau ! <br/> Pour toutes les images (sauf celle Haute qualité) il est possible de réduire le poid des images avec <a href='https://tinypng.com/' target='_blank'>Tiny PNG</a>"), "status");	
	
	}
	 
} 

/*
function NsHook_mail ($key, &$message, $params) {
  switch ($key) {
    	
      case 'mymail':
      // Set headers etc
      $message['to'] = 'p.delaunay1@gmail.com';
      $message['subject'] = t('Hello');
      $message['body'][] = t('Hello @username');
      $message['body'][] = t('The main part of the message.');
      drupal_set_message("Sent e-mail to p.delaunay1@gmail.com from module 3");
      break;
  }
}
*/

function NsHook_mail($key, &$message, $params){

  // Set the mail content type to html to send an html e-mail (optional).
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';

  // Grab the subject and body from params and add it to the message.
  $message['subject'] = $params['subject'];
  $message['body'][] = $params['body']; // Drupal 7
  //$message['body'] = $params['body']; // Drupal 6, I think

  switch ($key) {
    case "NsHook_mail_page_pro":
      // Make other changes here if desired...
      break;
  }

  //drupal_set_message("Sent e-mail to p.delaunay1@gmail.com from module 3");

}
  