<?php 
//MODULE DE HOOK NS  


function NsHook_form_alter(&$form, &$form_state, $form_id) {


	global $base_url;

	if (isset($form['type']) && $form['type']['#value'] == 'balade') {
	
		drupal_set_message(t("Nouveau ! <br/> Pour toutes les images (sauf celle Haute qualité) il est possible de réduire le poid des images avec <a href='https://tinypng.com/' target='_blank'>Tiny PNG</a>"), "status");

		//alter title
		$form['title']['#title'] = 'Titre de la balade (conserver le format : Balade de [Titre] ([CP]) - Région)  ';

		//alter field_balade_teaser 
		$form['field_balade_teaser']['und'][0]['#title'] = 'Ancienne description <span class="textAide">( Assurez-vous de saisir de champs sous le format Plain text )</span>';
		
		//Alter field_esp_ces
		$form['field_esp_ces']['und']['#title'] = 'Liste des espèces <span class="textAide">  - Cochez les espèces présente dans votre balade.</span>';
		
		foreach ($form['field_esp_ces']['und']['#options'] as $key => $value) {
			
			$form['field_esp_ces']['und']['#options'][$key] = "<a href='$base_url/node/$key'>$value</a>";
		
		}

	
	
	}else if (isset($form['type']) && $form['type']['#value'] == 'espece') {
	
		drupal_set_message(t("Nouveau ! <br/> Pour toutes les images (sauf celle Haute qualité) il est possible de réduire le poid des images avec <a href='https://tinypng.com/' target='_blank'>Tiny PNG</a>"), "status");	
	
	}
	 
} 
  	
  